LAB3/website/about/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r'^', views.index, name = 'index'),
]

LAB3/website/home/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r'^', views.index, name = 'index'),
]

LAB3/website/images/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^(?P<category_id>[0-9]+)/$', views.detail, name='detail'),
]

LAB3/website/website/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^about/', include('about.urls')),
    url(r'^images/', include('images.urls')),
    url(r'^$', include('home.urls')),
    url(r'^admin/', admin.site.urls),
]

LAB3/website/about/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

LAB3/website/home/models.py
from django.db import models

# Create your models here.

LAB3/website/images/models.py
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=64)
    year = models.CharField(max_length=5)
    category_logo = models.CharField(max_length=512)

    def __str__(self):
        return self.name

class Wallpaper(models.Model):
    category = models.ForeignKey(Category, on_delete= models.CASCADE)
    file_type = models.CharField(max_length=16)
    title = models.CharField(max_length=64)
    path = models.CharField(max_length=512)

    def __str__(self):
        return self.title

LAB3/website/images/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username', 'email', 'password']

LAB3/website/about/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'images/about.html')

LAB3/website/home/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from django.http import Http404
from django.shortcuts import render

def index(request):
    return render(request, 'images/home.html')

LAB3/website/images/views.py
from django.http import HttpResponse
from django.template import loader
from django.http import Http404
from .models import Category
from django.shortcuts import  render, redirect


def index(request):
    all_category = Category.objects.all()
    template = loader.get_template('images/index.html')
    context = { 'all_category': all_category,}
    return HttpResponse(template.render(context, request))

def detail(request, category_id):
    try:
        category = Category.objects.get(pk = category_id)
    except Category.DoesNotExist:
        raise Http404("Albumul nu exista")
    return render(request, 'images/detail.html', {'category' : category})

LAB3/website/images/templates/images/about.html
<style>
    body{
        background-color: black;
    }
p.font1 {
        text-align: center;
    color: white;
    font-family:"Lato Heavy";
    font-size: 50px;
    text-shadow: 4px 3px black;
    font-weight: bold;
}
p.font2 {
    color: white;
    font-family:"Lato Heavy";
    font-size: 30px;
    text-shadow: 4px 3px black;
    font-weight: bold;
}
p.font3 {
    color: white;
    font-family:"Lato Heavy";
    font-size: 20px;
    text-shadow: 4px 3px black;
    font-weight: bold;
}
    a {
     font-size: 25px;
    font-family:"Lato Heavy";
    color: white;
    text-shadow: 3px 2px black;
    text-decoration:none;

}
</style>
<p><b><a href="/" target="_blank"><-Home</a></b></p>
<p class="font1">About</p>
<p class="font2">Contacts</p>
<p class="font3">Bitca Ernest : 078079134</p>
<p class="font3">Oala Irina : 079878423</p>
<p class="font2">Tools:</p>
<p class="font3">Django</p>
<p class="font3">HTML</p>
<p class="font3">CSS</p>

LAB3/website/images/templates/images/detail.html
<style>
body {
        background-size: cover;
    background-repeat:   no-repeat;
    background-image: url("{{ category.category_logo }}");
    width: 100%;
    height: 100%;
}
</style>
<style>
p.font1 {
        text-align: center;
    color: white;
    font-family:"Lato Heavy";
    font-size: 50px;
    text-shadow: 4px 3px black;
    font-weight: bold;
}
p.font2 {
     font-size: 30px;
    text-shadow: 4px 3px black;
    font-family:"Lato Heavy";
    color: white;
}
a {
     font-size: 25px;
    font-family:"Lato Heavy";
    color: white;
    text-shadow: 3px 2px black;
    text-decoration:none;

}
</style>
<p class="font1">{{ category.name }}</p>
<p><b><a href="/images/" target="_blank"><-Categories</a></b>
<p class="font2">Year: {{ category.year }}</p>
    {% for wallpaper in category.wallpaper_set.all%}
        <div style="text-align:center">
        <p><b><a href="{{ wallpaper.path }}" target="_blank">{{ wallpaper.title }}</a></b></p>
        </div>
    {% endfor %}

LAB3/website/images/templates/images/home.html
<style>
    body{
            background-size: cover;

         background-image: url("https://s-media-cache-ak0.pinimg.com/originals/08/4a/1f/084a1ff2aa19b30cd175f68664d338c0.jpg");
    }
a.one {
     font-size: 35px;
    font-family:"Lato Heavy";
    color: black;
    text-align: center;
    text-shadow: 1px 1px black;
    text-decoration:none;
     position: fixed;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}

a.two {
    font-size: 17px;
    font-family:"Lato Heavy";
    color: white;
    display: inline;
    text-align: right;
    text-shadow: 2px 1px black;
    text-decoration:none;
}
    .Row
{
    display: table;
    width: 100%; /*Optional*/
    table-layout: fixed; /*Optional*/
    border-spacing: 10px; /*Optional*/
}
.Column1
{
    display: table-cell;
    background:rgba(255,255,255,0.5);
}
.Column2
{
    display: table-cell;
    background:rgba(255,255,255,0.0);
}
    p.font2 {
     font-size: 18px;
    text-shadow: 2px 1px black;
    font-family:"Lato Heavy";
    color: white;
}
     p.font1 {
     font-size: 15px;
    font-family:"Lato Heavy";
    color: black;
}
</style>

<div style="text-align:right" >
    <p><b><a class="two" href="about/" target="_blank">About</a></b></p>
</div>
<div style="text-align:center">
<p><b><a class="one" href="images/" target="_blank">>-Wallpapers App-<</a></b></p>
</div>
<div class="Row">
    <div class="Column2" style="text-align:center"><p class="font2">Wallpapers app</p></div>
    <div class="Column2" style="text-align:center"><p class="font2">Music app</p></div>
    <div class="Column2" style="text-align:center"><p class="font2">Video app</p></div>
</div>
<div class="Row">
    <div class="Column1"><p class="font1">This application allows
you to view our Wallpapers. Actually there are 4 categories. More-coming soon !.
        If you think that you have nice wallpaperes,
        you can send them to our administrator.</p></div>
    <div class="Column1"><p class="font1">Music App is in construction at the moment.
        This app will allow you to download your favorite songs from our website. Also you will be able to add your
    own songs and share them with your friends.</p></div>
    <div class="Column1"><p class="font1">Video App is an app which contain a collection of video tutorials.
        In this way you can enhance your skills very easy.
        There will be categories like cooking, programming and sport.
    </p></div>
</div>
<div style="text-align:left; position: fixed; bottom: 0; left: 0;">
    <p class="font2">ernest.bitca@gmail.com</p>
</div>

LAB3/website/images/templates/images/index.html
<style>
html, body { height: 100%; padding: 0; margin: 0; }
div { width: 50%; height: 50%; float: left; }
#div1 {}
#div2 {}
#div3 {}
#div4 {}

.bgimg1 {
    background-image: url('https://wallpaperscraft.com/image/ford_mustang_aristo_night_cars_108990_1920x1080.jpg');
    background-size: contain;
        background-repeat: no-repeat;
    background-size:cover;
}
.bgimg2 {
    background-image: url('http://38.media.tumblr.com/d483f1a18b18b5f29c7089908d151386/tumblr_nazctmUqOI1tv4hrso3_1280.jpg');
    background-size: contain;
    background-size:cover;
}
.bgimg3 {
    background-image: url('http://www.wallpapers.rs/wallpapers/cat_and_technology-1920x1080.jpg');
    background-size: contain;
    background-size: cover;

}
.bgimg4 {
    background-image: url('http://www.loversiq.com/daut/as/f/e/exterior-design-modern-house-elevation-architecture-excerpt-homes_beautiful-houses-interior-and-exterior-photos_interior-design_interior-design-software-free-major-school-designing-living-room-portfol.jpg');
    background-size: contain;
    background-size:cover;
}
a {
     font-size: 25px;
    font-family:"Lato Heavy";
    color: white;
    text-shadow: 3px 2px black;
    text-decoration:none;
}
a.two
{
     font-size: 25px;
    font-family:"Lato Heavy";
    color: white;
    text-shadow: 3px 2px black;
    text-align: left;
    text-decoration:none;
     text-decoration:none;
     position: fixed;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}
</style>
<a class="two" href = "/">Home</a>
<div style="text-align:center" id="div1" class="bgimg1">
    <a href = "/images/1">Cars</a>
</div>

<div style="text-align:center" id="div2" class="bgimg2">
    <a href = "/images/2">Nature</a>
</div>

<div style="text-align:center" id="div3" class="bgimg3">
    <a href = "/images/3">Technology</a>
</div>

<div style="text-align:center" id="div4" class="bgimg4">
    <a href = "/images/4">Architecture Design</a>
</div>